version: '3'

services:
  db:
    image: postgres:11.2
    restart: unless-stopped
    volumes:
      # FIXME: max connections raised from 100 to 1000 in
      # docker-volumes/db/postgresql.conf
      - ./docker-volumes/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: fluentd
      options:
        tag: nextcloud.db
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'

  app:
    image: nextcloud:20.0.6-apache
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./docker-volumes/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_HOST: db
      VIRTUAL_HOST: ${APP_VIRTUAL_HOST}
      NEXTCLOUD_TRUSTED_DOMAINS: ${APP_VIRTUAL_HOST}
    depends_on:
      - db
    networks:
      - proxy-tier
      - default # to connect to db
    labels:
      traefik.http.routers.app.rule: Host(`${APP_VIRTUAL_HOST}`)
      traefik.http.routers.app.tls: true
      traefik.http.routers.app.tls.certresolver: le
      traefik.http.services.app.loadbalancer.server.port: 80
      traefik.docker.network: nextcloud_proxy-tier
      traefik.http.routers.app.middlewares: dav_discovery
      traefik.http.middlewares.dav_discovery.redirectregex.regex: /.well-known/(card|cal)dav
      traefik.http.middlewares.dav_discovery.redirectregex.replacement: /remote.php/dav/
    logging:
      driver: fluentd
      options:
        tag: nextcloud.app
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'

  app-cron:
    image: nextcloud:20.0.4-apache
    entrypoint: /cron.sh
    restart: unless-stopped
    volumes:
      - ./docker-volumes/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - app
    networks:
      - default

  code:
    image: collabora/code:6.4.5.3
    restart: unless-stopped
    expose:
      - 9980
    cap_add:
      - MKNOD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      domain: ${APP_VIRTUAL_HOST}
      username: ${CODE_USERNAME}
      password: ${CODE_PASSWORD}
    networks:
      - proxy-tier
    labels:
      traefik.http.routers.code.rule: Host(`${CODE_VIRTUAL_HOST}`)
      traefik.http.routers.code.tls: true
      traefik.http.routers.code.tls.certresolver: le
      traefik.http.services.code.loadbalancer.server.port: 9980
      traefik.http.services.code.loadbalancer.server.scheme: https
    logging:
      driver: fluentd
      options:
        tag: nextcloud.code
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'

networks:
  default:
