version: '3'

# before the ES index for fluentd gets created, you'll need to run the
# following query (either in the kibana console, or via curl) so that
# location_array is properly handled as a geopoint; make sure you do
# this after ES has been started, but before fluentd starts:
#  
# PUT _template/fluentd
# {
#   "index-patterns: "fluentd-*",
#   "mappings": {
#     "properties" : {
#         "location_array": { "type": "geo_point"}
#     }
#   }
# }

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
    restart: unless-stopped
    volumes:
      # local dir neeeds to be chown'ed 1000:1000
      - ./docker-volumes/elasticsearch:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    expose:
      - 9200
      - 9300
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      discovery.type: single-node
    networks:
      - efk

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.0
    restart: unless-stopped
    expose:
      - 5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - elasticsearch
    networks:
      - proxy-tier
      - efk
    labels:
      traefik.enable: true
      traefik.docker.network: nextcloud_proxy-tier
      traefik.http.routers.kibana.rule: Host(`${KIBANA_VIRTUAL_HOST}`)
      traefik.http.routers.kibana.tls: true
      traefik.http.routers.kibana.tls.certresolver: le
      traefik.http.services.kibana.loadbalancer.server.port: 5601
      traefik.http.routers.kibana.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: ${TRAEFIK_AUTH_USER}
      traefik.docker.network: nextcloud_proxy-tier

  fluentd:
    build:
      context: ./fluentd
    restart: unless-stopped
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - efk
    ports:
      - "127.0.0.1:24224:24224"

networks:
  efk:
    driver: bridge
