version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
    volumes:
      # local dir neeeds to be chown'ed 1000:1000
      - ./docker-volumes/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - efk

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - efk

  fluentd:
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - efk
    ports:
      - "127.0.0.1:24224:24224"

networks:
  efk:
    driver: bridge
