version: '3'

services:
  db:
    image: postgres:11.2
    restart: always
    volumes:
      # FIXME: max connections raised from 100 to 1000 in
      # docker-volumes/db/postgresql.conf
      - ./docker-volumes/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - db.env

  app:
    image: nextcloud:15.0-apache
    restart: always
    volumes:
      - ./docker-volumes/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_HOST: db
      VIRTUAL_HOST: nextcloud.some-domain.com
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.some-domain.com
      LETSENCRYPT_HOST: nextcloud.some-domain.com
      LETSENCRYPT_EMAIL: user@provider.com
    env_file:
      - app.env
    depends_on:
      - db
    networks:
      - proxy-tier
      - default # to connect to db

  code:
    image: collabora/code:4.0.3.1
    restart: always
    expose:
      - 9980
    cap_add:
      - MKNOD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      domain: nextcloud.some-domain.com
      username: some-login
      password: yet-another-long-password
      VIRTUAL_HOST: collabora.some-domain.com
      VIRTUAL_NETWORK: proxy-tier
      # shouldn't be needed since this container only exposes one port
      VIRTUAL_PORT: 9980
      VIRTUAL_PROTO: https
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: collabora.some-domain.com
      LETSENCRYPT_EMAIL: user@provider.com
    networks:
      - proxy-tier

  proxy:
    image: jwilder/nginx-proxy:alpine-20190516
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./docker-volumes/proxy/certs:/etc/nginx/certs:ro
      - ./docker-volumes/proxy/vhost.d:/etc/nginx/vhost.d
      - ./docker-volumes/proxy/html:/usr/share/nginx/html
      - ./proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
      - ./proxy/buffersize.conf:/etc/nginx/conf.d/buffersize.conf:ro
      - ./proxy/network_internal.conf:/etc/nginx/network_internal.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.10
    restart: always
    volumes:
      - ./docker-volumes/proxy/certs:/etc/nginx/certs
      - ./docker-volumes/proxy/vhost.d:/etc/nginx/vhost.d
      - ./docker-volumes/proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - proxy
    networks:
      - proxy-tier

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
    volumes:
      - ./docker-volumes/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - efk
    logging:
      driver: fluentd
      options:
        tag: efk.elasticsearch
    depends_on:
      - fluentd        

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    expose:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - efk
    logging:
      driver: fluentd
      options:
        tag: efk.kibana  

  fluentd:
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - efk
    expose:
      - "24224:24224"
      - "24224:24224/udp"

networks:
  proxy-tier:
  default:
  efk:
    driver: bridge
