version: '3'

services:
  traefik:
    image: traefik:2.4.2
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --log.level=INFO
      - --api.dashboard=true
      - --serverstransport.insecureskipverify=true
      - --accesslog.format=common
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-volumes/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    labels:
      traefik.enable: true
      traefik.docker.network: nextcloud_proxy-tier
      traefik.http.routers.api.rule: Host(`${TRAEFIK_VIRTUAL_HOST}`)
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.entrypoints: websecure
      traefik.http.routers.api.tls.certresolver: le
      traefik.http.routers.api.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: ${TRAEFIK_AUTH_USER}

  db:
    image: postgres:11.2
    command: postgres -c 'max_connections=1000'
    restart: unless-stopped
    volumes:
      - ./docker-volumes/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  app:
    image: nextcloud:24.0.0-apache
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./docker-volumes/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      VIRTUAL_HOST: ${APP_VIRTUAL_HOST}
      NEXTCLOUD_TRUSTED_DOMAINS: ${APP_VIRTUAL_HOST}
    links:
      - db
    networks:
      - proxy-tier
      - default # to connect to db
    labels:
      traefik.enable: true
      traefik.docker.network: nextcloud_proxy-tier
      traefik.http.routers.app.rule: Host(`${APP_VIRTUAL_HOST}`)
      traefik.http.routers.app.entrypoints: websecure
      traefik.http.routers.app.tls.certresolver: le
      traefik.http.services.app.loadbalancer.server.port: 80
      traefik.http.routers.app.middlewares: dav_discovery
      traefik.http.middlewares.dav_discovery.redirectregex.regex: /.well-known/(card|cal)dav
      traefik.http.middlewares.dav_discovery.redirectregex.replacement: /remote.php/dav/

  app-cron:
    image: nextcloud:23.0.2-apache
    entrypoint: /cron.sh
    restart: unless-stopped
    volumes:
      - ./docker-volumes/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - app
    networks:
      - default

  code:
    image: collabora/code:21.11.4.2.1
    restart: unless-stopped
    expose:
      - 9980
    cap_add:
      - MKNOD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      aliasgroup1: https://${APP_VIRTUAL_HOST}:443
      username: ${CODE_USERNAME}
      password: ${CODE_PASSWORD}
    networks:
      - proxy-tier
    labels:
      traefik.enable: true
      traefik.docker.network: nextcloud_proxy-tier
      traefik.http.routers.code.rule: Host(`${CODE_VIRTUAL_HOST}`)
      traefik.http.routers.code.entrypoints: websecure
      traefik.http.routers.code.tls.certresolver: le
      traefik.http.services.code.loadbalancer.server.port: 9980
      traefik.http.services.code.loadbalancer.server.scheme: https

networks:
  default:
  proxy-tier:
