version: '3'

# before the ES index for fluentd gets created, you'll need to run the
# following query (either in the kibana console, or via curl) so that
# location_array is properly handled as a geopoint; make sure you do
# this after ES has been started, but before fluentd starts:
#  
# PUT _template/fluentd
# {
#   "index-patterns: "fluentd-*",
#   "mappings": {
#     "properties" : {
#         "location_array": { "type": "geo_point"}
#     }
#   }
# }

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
    volumes:
      # local dir neeeds to be chown'ed 1000:1000
      - ./docker-volumes/elasticsearch:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    expose:
      - 9200
      - 9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - efk

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - efk

  fluentd:
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - efk
    ports:
      - "127.0.0.1:24224:24224"

networks:
  efk:
    driver: bridge
